// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from song.djinni

package com.skycatch.jnigenpackage;

public final class Song {


    /*package*/ final String title;

    /*package*/ final String artist;

    public Song(
            String title,
            String artist) {
        this.title = title;
        this.artist = artist;
    }

    public String getTitle() {
        return title;
    }

    public String getArtist() {
        return artist;
    }

    @Override
    public String toString() {
        return "Song{" +
                "title=" + title +
                "," + "artist=" + artist +
        "}";
    }

}
