// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from song.djinni

#pragma once

#include "djinni_support.hpp"
#include "song.hpp"

namespace djinni_generated {

class NativeSong final {
public:
    using CppType = ::Song;
    using JniType = jobject;

    using Boxed = NativeSong;

    ~NativeSong();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeSong();
    friend ::djinni::JniClass<NativeSong>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/skycatch/jnigenpackage/Song") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljava/lang/String;Ljava/lang/String;)V") };
    const jfieldID field_title { ::djinni::jniGetFieldID(clazz.get(), "title", "Ljava/lang/String;") };
    const jfieldID field_artist { ::djinni::jniGetFieldID(clazz.get(), "artist", "Ljava/lang/String;") };
};

}  // namespace djinni_generated
