// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from song.djinni

#import "SKYSong+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto Song::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::String::toCpp(obj.title),
            ::djinni::String::toCpp(obj.artist)};
}

auto Song::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[SKYSong alloc] initWithTitle:(::djinni::String::fromCpp(cpp.title))
                                   artist:(::djinni::String::fromCpp(cpp.artist))];
}

}  // namespace djinni_generated
