// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from song.djinni

#import "SKYSong.h"
#include "song.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class SKYSong;

namespace djinni_generated {

struct Song
{
    using CppType = ::Song;
    using ObjcType = SKYSong*;

    using Boxed = Song;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
