// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from song.djinni

#import "SKYSong.h"


@implementation SKYSong

- (nonnull instancetype)initWithTitle:(nonnull NSString *)title
                               artist:(nonnull NSString *)artist
{
    if (self = [super init]) {
        _title = [title copy];
        _artist = [artist copy];
    }
    return self;
}

+ (nonnull instancetype)songWithTitle:(nonnull NSString *)title
                               artist:(nonnull NSString *)artist
{
    return [[self alloc] initWithTitle:title
                                artist:artist];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p title:%@ artist:%@>", self.class, self, self.title, self.artist];
}

@end
