// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from song.djinni

#import <Foundation/Foundation.h>

@interface SKYSong : NSObject
- (nonnull instancetype)initWithTitle:(nonnull NSString *)title
                               artist:(nonnull NSString *)artist;
+ (nonnull instancetype)songWithTitle:(nonnull NSString *)title
                               artist:(nonnull NSString *)artist;

@property (nonatomic, readonly, nonnull) NSString * title;

@property (nonatomic, readonly, nonnull) NSString * artist;

@end
